name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # change if needed

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build & push Rocket.Chat image
      - name: Build and push Rocket.Chat
        run: |
          docker build -t rocketchat ./rocketchat
          docker tag rocketchat:latest 099751327699.dkr.ecr.us-east-1.amazonaws.com/rocketchat:latest
          docker push 099751327699.dkr.ecr.us-east-1.amazonaws.com/rocketchat:latest

      # Build & push Mongo image
      - name: Build and push Mongo
        run: |
          docker build -t mongo ./mongo
          docker tag mongo:latest 099751327699.dkr.ecr.us-east-1.amazonaws.com/mongo:latest
          docker push 099751327699.dkr.ecr.us-east-1.amazonaws.com/mongo:latest
