name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Rocket.Chat
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rajeshchoco/rocketchat:7.9.3

      - name: Push Mongo (re-tag official image)
        run: |
          docker pull mongo:6.0
          docker tag mongo:6.0 rajeshchoco/mongo:6.0
          docker push rajeshchoco/mongo:6.0
